name: "Release (latest)"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  scheduled_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Explicitly pass in the sha, even though it's very likely to be HEAD.
      - run: hub release create --prerelease --message "Automated build. Do not use in production." -t ${{ github.sha }} "release-$(date +%Y%m%d.%H%M)"

        # Propagate token into environment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Even though the release job has an on: release trigger, actions taken by GITHUB_TOKEN
  # don't trigger this, so we call it here
  # https://docs.github.com/en/actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow
  release:
    needs: scheduled_release
    uses: ./.github/workflows/release_artifacts.yml
