name: Windows

on:
  workflow_call:

jobs:
  benchmark:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      # Windows benchmarking is currently broken!
      # See See https://github.com/tigerbeetledb/tigerbeetle/issues/473
      # - run: ./scripts/benchmark.bat
